### ISSUE TITLE
Fix syck dependency

### ISSUE THREAD

**Issue by invadersmustdie** [invadersmustdie/puppet-catalog-test#23]
See: [https://travis-ci.org/invadersmustdie/puppet-catalog-test/jobs/107865658](https://travis-ci.org/invadersmustdie/puppet-catalog-test/jobs/107865658)
<code>
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ rvm --version
rvm 1.26.10 (1.26.10) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.11.2
$ gem --version
2.5.1
travis_fold:start:install.bundler
[0Ktravis_time:start:0b1c09a2
[0K$ bundle install --jobs=3 --retry=3
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
[32mInstalling CFPropertyList 2.2.8[0m
[32mInstalling rake 10.5.0[0m
[32mInstalling builder 3.2.2[0m
[32mInstalling facter 2.4.6[0m
[32mInstalling json_pure 1.8.3[0m
[32mInstalling metaclass 0.0.4[0m
[32mInstalling parallel 1.6.1[0m
Using bundler 1.11.2
[32mInstalling power_assert 0.2.7[0m
[32mInstalling hiera 1.3.4[0m
[32mInstalling mocha 0.14.0[0m
[32mInstalling test-unit 3.1.7[0m
[32mInstalling hiera-puppet 1.0.0[0m
[32mInstalling puppet 3.8.5[0m
[32mBundle complete! 8 Gemfile dependencies, 14 gems now installed.[0m
[32mUse `bundle show [gemname]` to see where a bundled gem is installed.[0m

travis_time:end:0b1c09a2:start=1454965148487975145,finish=1454965155094765330,duration=6606790185
[0Ktravis_fold:end:install.bundler
[0Ktravis_time:start:2ea19716
[0K$ bundle exec rake
/home/travis/.rvm/rubies/ruby-2.3.0/bin/ruby -I"lib:test" -I"/home/travis/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib" "/home/travis/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/complete_catalog_test.rb" "test/hiera_test.rb" "test/reporter_test.rb" "test/scenario_test.rb" 
/home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>': uninitialized constant Syck (NameError)
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `require'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `<module:YAML>'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:132:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet/vendor/require_vendored.rb:4:in `require'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet/vendor/require_vendored.rb:4:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet/vendor.rb:40:in `require'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet/vendor.rb:40:in `require_libs'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet/vendor.rb:53:in `load_vendored'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet.rb:174:in `<module:Puppet>'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/puppet-3.8.5/lib/puppet.rb:29:in `<top (required)>'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/lib/puppet-catalog-test/puppet_adapter/base_puppet_adapter.rb:1:in `require'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/lib/puppet-catalog-test/puppet_adapter/base_puppet_adapter.rb:1:in `<top (required)>'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/lib/puppet-catalog-test/puppet_adapter_factory.rb:2:in `require'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/lib/puppet-catalog-test/puppet_adapter_factory.rb:2:in `<top (required)>'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/lib/puppet-catalog-test/test_runner.rb:6:in `require'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/lib/puppet-catalog-test/test_runner.rb:6:in `<top (required)>'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/lib/puppet-catalog-test.rb:7:in `require'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/lib/puppet-catalog-test.rb:7:in `<module:PuppetCatalogTest>'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/lib/puppet-catalog-test.rb:1:in `<top (required)>'
	from test/test_helper.rb:6:in `require'
	from test/test_helper.rb:6:in `<top (required)>'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/test/complete_catalog_test.rb:1:in `load'
	from /home/travis/build/invadersmustdie/puppet-catalog-test/test/complete_catalog_test.rb:1:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `require'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/travis/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/travis/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib" "/home/travis/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/complete_catalog_test.rb" "test/hiera_test.rb" "test/reporter_test.rb" "test/scenario_test.rb" ]
/home/travis/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
</code

**Comment by invadersmustdie** [comment]
fixed
